import { ColumnMatch, MatcherResult } from './column-matcher';
import { TableType } from '../rules/rule.types';

export interface YamlGeneratorInput {
  oldTable: string;
  newTable: string;
  tableType: TableType;
  result: MatcherResult;
}

export function generateYaml(input: YamlGeneratorInput): string {
  const { oldTable, newTable, tableType, result } = input;
  const { matches, anchorOld, anchorNew } = result;

  const lines: string[] = [];

  lines.push(`# AUTO-GENERATED by /schema/analyze — review before moving to rules/`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push(``);
  lines.push(`table_info:`);
  lines.push(`  source: "${oldTable}"`);
  lines.push(`  target: "${newTable}"`);
  lines.push(`  table_type: ${tableType}`);
  lines.push(``);
  const overlapNote = result.anchorOverlapPct !== null
    ? `  # AUTO-DETECTED — ${result.anchorOverlapPct}% value overlap — verify before use`
    : `  # AUTO-DETECTED — verify before use`;
  lines.push(`anchor_key:`);
  lines.push(`  old: ${anchorOld ?? 'UNKNOWN'}   ${overlapNote}`);
  lines.push(`  new: ${anchorNew ?? 'UNKNOWN'}`);
  lines.push(``);
  lines.push(`schema_mappings:`);

  // ---- exact_matches (VERIFIED without transform hint) ----
  const exactVerified = matches.filter(
    (m) => m.status === 'VERIFIED' && m.transformHint === 'NONE' && m.newCol,
  );
  const exactProbable = matches.filter(
    (m) => m.status === 'PROBABLE' && m.transformHint === 'NONE' && m.newCol,
  );

  lines.push(`  exact_matches:`);
  if (exactVerified.length > 0) {
    lines.push(`    # VERIFIED (high confidence):`);
    for (const m of exactVerified) {
      lines.push(`    - old: ${m.oldCol.name}`);
      lines.push(`      new: ${m.newCol!.name}`);
    }
  }
  if (exactProbable.length > 0) {
    lines.push(`    # PROBABLE — review these:`);
    for (const m of exactProbable) {
      lines.push(`    - old: ${m.oldCol.name}`);
      lines.push(`      new: ${m.newCol!.name}  # confidence: ${(m.confidence * 100).toFixed(0)}%`);
    }
  }
  if (exactVerified.length === 0 && exactProbable.length === 0) {
    lines.push(`    [] # no exact matches detected`);
  }

  // ---- transformed_matches (VERIFIED/PROBABLE with transform hint) ----
  const transformed = matches.filter(
    (m) => (m.status === 'VERIFIED' || m.status === 'PROBABLE') && m.transformHint !== 'NONE' && m.newCol,
  );

  lines.push(``);
  lines.push(`  transformed_matches:`);
  if (transformed.length > 0) {
    for (const m of transformed) {
      const prefix = m.status === 'PROBABLE' ? `    # PROBABLE — ` : `    # `;
      if (m.status === 'VERIFIED') {
        lines.push(`    - old: ${m.oldCol.name}`);
        lines.push(`      new: ${m.newCol!.name}`);
        lines.push(`      transform_rule: ${m.transformHint}`);
      } else {
        lines.push(`${prefix}${m.transformHint} hint:`);
        lines.push(`    # - old: ${m.oldCol.name}`);
        lines.push(`    #   new: ${m.newCol!.name}  # confidence: ${(m.confidence * 100).toFixed(0)}%`);
        lines.push(`    #   transform_rule: ${m.transformHint}`);
      }
    }
  } else {
    lines.push(`    [] # no transform matches detected`);
  }

  // ---- MANUAL_CHECK (commented out) ----
  const manualCheck = matches.filter((m) => m.status === 'MANUAL_CHECK' && m.newCol);
  if (manualCheck.length > 0) {
    lines.push(``);
    lines.push(`  # MANUAL_CHECK — low confidence, review these:`);
    for (const m of manualCheck) {
      lines.push(`  # - old: ${m.oldCol.name}`);
      lines.push(`  #   new: ${m.newCol!.name}  # confidence: ${(m.confidence * 100).toFixed(0)}%`);
      if (m.transformHint !== 'NONE') {
        lines.push(`  #   transform_rule: ${m.transformHint}  # hint only`);
      }
    }
  }

  // ---- SAME_NAME_DIFF_DATA (omitted from mappings, explained in comment) ----
  const sameNameDiff = matches.filter((m) => m.status === 'SAME_NAME_DIFF_DATA');
  if (sameNameDiff.length > 0) {
    lines.push(``);
    lines.push(`  # SAME_NAME_DIFF_DATA — column name matches but data has zero overlap.`);
    lines.push(`  # This usually means the field was renumbered/re-keyed during migration.`);
    lines.push(`  # DO NOT map these directly — investigate the business logic first:`);
    for (const m of sameNameDiff) {
      lines.push(`  #   ${m.oldCol.name} (old format: ${m.oldCol.sampleValues[0] ?? 'n/a'}) → ${m.newCol?.name ?? 'no candidate'} (new format: ${m.newCol?.sampleValues[0] ?? 'n/a'})`);
    }
  }

  // ---- REGENERATED_ID ----
  const regeneratedIds = matches.filter((m) => m.status === 'REGENERATED_ID');
  if (regeneratedIds.length > 0) {
    lines.push(``);
    lines.push(`  # REGENERATED_ID — system-generated primary key (id column).`);
    lines.push(`  # Old and new IDs are from different sequences — do not map:`);
    for (const m of regeneratedIds) {
      lines.push(`  #   ${m.oldCol.name}: old=${m.oldCol.sampleValues[0] ?? 'n/a'}`);
    }
  }

  return lines.join('\n') + '\n';
}
